FROM ubuntu:22.04

LABEL Description="Cross-compile build environment arm32v7"

RUN apt-get update \
    && apt-get install gcc-arm-linux-gnueabi -y \
    && apt-get install g++-arm-linux-gnueabi -y \
    && apt-get install cmake -y

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

ENTRYPOINT [ "/bin/bash", "-l", "-c" ]


