set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(TOOLCHAIN_ROOT_DIR "/usr/bin")
set(TOOLCHAIN_PREFIX   "arm-linux-gnueabi")

set(CMAKE_FIND_ROOT_PATH /usr/${TOOLCHAIN_PREFIX})

set(CMAKE_AR            ${TOOLCHAIN_ROOT_DIR}/${TOOLCHAIN_PREFIX}-ar     )
set(CMAKE_ASM_COMPILER  ${TOOLCHAIN_ROOT_DIR}/${TOOLCHAIN_PREFIX}-as     )
set(CMAKE_C_COMPILER    ${TOOLCHAIN_ROOT_DIR}/${TOOLCHAIN_PREFIX}-gcc    )
set(CMAKE_CXX_COMPILER  ${TOOLCHAIN_ROOT_DIR}/${TOOLCHAIN_PREFIX}-g++    )
set(CMAKE_LINKER        ${TOOLCHAIN_ROOT_DIR}/${TOOLCHAIN_PREFIX}-ld     )
set(CMAKE_OBJCOPY       ${TOOLCHAIN_ROOT_DIR}/${TOOLCHAIN_PREFIX}-objcopy)
set(CMAKE_RANLIB        ${TOOLCHAIN_ROOT_DIR}/${TOOLCHAIN_PREFIX}-ranlib )
set(CMAKE_SIZE          ${TOOLCHAIN_ROOT_DIR}/${TOOLCHAIN_PREFIX}-size   )
set(CMAKE_STRIP         ${TOOLCHAIN_ROOT_DIR}/${TOOLCHAIN_PREFIX}-strip  )

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
